### ISSUE TITLE
UI object creation

### ISSUE THREAD

**Issue by Cash120** [dylan-mcleod/FLC-Breakout#9]
Also add:
-Title
-Pause
-Ending Win/Loss

**Comment by Cash120** [comment]
Sean will write the UI object code

**Comment by Edopad** [comment]
Not knowing this was an assigned issue, I created the game Scene framework and made a few example scenes, like those mentioned in the description of this issue (Title, Pause).

However, I did not do anything useful in any of the classes; they are blank or basic and require coding to make them useful.

**Comment by ghost** [comment]
Gonna mark this closed for now.  If we need to be able to add images or sliders to menus in the future, that shouldn't be too difficult to add, but we might not necessarily need those things
